"""
Kaizen Opportunities API — Returns live opportunities from the Kaizen worker.
"""
from fastapi import APIRouter
from datetime import datetime

from app.services.redis_store import get_kaizen_opportunities, get_current_state, BAT_SEC_KWH_T_CLINKER

router = APIRouter()


@router.get("")
async def get_kaizen():
    """Return live Kaizen opportunities from Redis (generated by kaizen_worker)."""
    opportunities = await get_kaizen_opportunities()
    state = await get_current_state()

    # Compute live Kaizen score
    total_power = state.get("PLANT-TOTAL-POWER", 18400.0)
    clinker_tph = state.get("KILN-CLINKER-PROD", 185.0)
    sec = (total_power / clinker_tph) if clinker_tph > 0 else 64.2
    sec_deviation = max(0, ((sec - BAT_SEC_KWH_T_CLINKER) / BAT_SEC_KWH_T_CLINKER) * 100)
    kaizen_score = max(0, 100 - sec_deviation * 5 - len(opportunities) * 1)

    total_saving_inr = sum(o.get("saving_inr_day", 0) for o in opportunities)
    total_saving_kwh = sum(o.get("saving_kwh_day", 0) for o in opportunities)

    # If worker hasn't generated opportunities yet, return placeholder
    if not opportunities:
        opportunities = [{
            "id": "KAI-INIT",
            "title": "Analysing plant data for opportunities...",
            "department": "PLANT",
            "description": "Kaizen worker is computing opportunities. Check back in ~30 seconds.",
            "saving_inr_day": 0,
            "saving_kwh_day": 0,
            "priority": "LOW",
            "advisory": True,
            "created_at": datetime.utcnow().isoformat() + "Z",
        }]
        kaizen_score = 85.0

    return {
        "opportunities": opportunities,
        "total": len(opportunities),
        "total_potential_saving_inr_day": round(total_saving_inr, 0),
        "total_potential_saving_kwh_day": round(total_saving_kwh, 0),
        "kaizen_score": round(kaizen_score, 1),
        "sec_current": round(sec, 1),
        "sec_target": BAT_SEC_KWH_T_CLINKER,
        "timestamp": datetime.utcnow().isoformat() + "Z",
    }
